# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

import sys

sys.path.append("/Workspace/Users/singamshiva78_gmail.com#ext#@singamshiva78gmail.onmicrosoft.com/Azure-DataOps-Pipeline/Databricks/New Pipeline 2026-03-23 22:40")

# COMMAND ----------

# !!! Before performing any data analysis, make sure to run the pipeline to materialize the sample datasets. The tables referenced in this notebook depend on that step.

display(spark.sql("SELECT * FROM nyctaxi.taxi_db.sample_aggregation_mar_23_2240"))
